In [1]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    'Date': pd.date_range('2026-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

In [7]:
df = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    333     74   John
1  2023-01-02       B   West    721     87   Mary
2  2023-01-03       C  North    868     12    Bob
3  2023-01-04       D  South    744     14  Alice
4  2023-01-05       A   East    143     37   John
5  2023-01-06       B   West    821     11   Mary
6  2023-01-07       C  North    467     32    Bob
7  2023-01-08       D  South    591     76  Alice
8  2023-01-09       A   East    368     28   John
9  2023-01-10       B   West    691     90   Mary
10 2023-01-11       C  North    500     35    Bob
11 2023-01-12       D  South    129     22  Alice
12 2023-01-13       A   East    535     69   John
13 2023-01-14       B   West    966     22   Mary
14 2023-01-15       C  North    371     56    Bob
15 2023-01-16       D  South    735     55  Alice
16 2023-01-17       A   East    929     27   John
17 2023-01-18       B   West    609     40   Mary
18 2023-01-19       C  North    862     39    Bob
19 2023-01-20       D  South    893     40  Alice

In [5]:
pd.pivot_table(df,values = "Sales", index = "Region",columns="Product")

Product      A      B      C      D
Region
East     461.6    NaN    NaN    NaN
North      NaN    NaN  613.6    NaN
South      NaN    NaN    NaN  618.4
West       NaN  761.6    NaN    NaN

data → your DataFrame
values → column to aggregate
index → rows grouping
columns → column grouping
aggfunc → function like "sum", "mean", "count"

In [8]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     461.6    NaN    NaN    NaN  47.0   NaN   NaN   NaN
North      NaN    NaN  613.6    NaN   NaN   NaN  34.8   NaN
South      NaN    NaN    NaN  618.4   NaN   NaN   NaN  41.4
West       NaN  761.6    NaN    NaN   NaN  50.0   NaN   NaN

In [ ]:
pd.crosstab(df['Region'],df['Product'])
#cross tabs gives the count but pivot_tables give the aggregation function

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0